crud/urls.py
from django.urls import path

from crud.views import contact

app_name = "crud"
urlpatterns = [
    path('', contact.index, name='index'),
    path('validate_telephone/', contact.validate_telephone, name='validate_telephone'),
    path('create/', contact.create, name='create'),
    path('delete/<int:pk>/', contact.delete, name='delete'),
    path('show/<int:pk>/', contact.show, name='show'),
    path('update/<int:pk>/', contact.update, name='update'),
]

dt_task/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView



urlpatterns = [
    path('crud/', include('crud.urls')),
    path("admin/", admin.site.urls),
    path('', RedirectView.as_view(url='crud/', permanent=True)),
]

crud/models/contact.py
from django.db import models
from django.urls import reverse

from django.contrib.auth.models import User

class Contact(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    telephone = models.CharField(max_length=200, unique=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)
    

    def __str__(self):
        return self.telephone

    def get_absolute_url(self):
        return reverse("crud:show", kwargs={"pk": self.pk})

crud/forms/contact_form.py
from django import forms

from crud.models.contact import Contact

class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = ["name", "telephone", "address"]

crud/forms/update_contact_form.py
from django import forms

from crud.models.contact import Contact

class UpdateContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = ["name", "telephone", "address", "id"]

crud/views/contact.py
from django.shortcuts import render
from django.views.decorators.http import require_GET, require_POST
from django.http import JsonResponse
from django.core import serializers

from crud.forms.contact_form import ContactForm
from crud.forms.update_contact_form import UpdateContactForm
from crud.models.contact import Contact


def index(request):
    try:
        skip = int(request.GET.get("skip")) if request.GET.get("skip") else 0
        limit = int(request.GET.get("limit")) if request.GET.get("limit") else 20
        contacts = Contact.objects.all()[skip:limit]
        
        return render(request, 'crud/contact.html', {"contacts": contacts})
    except ValueError:
        return JsonResponse({"errors": 'An Error occur'})

def validate_telephone(request):
    """Check username availability"""
    telephone = request.GET.get('telephone', None)
    response = {
        'is_taken': Contact.objects.filter(telephone__iexact=telephone).exists()
    }
    return JsonResponse(response)

@require_POST
def create(request):
    form = ContactForm(request.POST)
    if form.is_valid():
        telephone = form.cleaned_data['telephone']
        form.save()
        return JsonResponse({"telephone": telephone}, status=200)
    else:
        errors = form.errors.as_json()
        return JsonResponse({"errors": errors}, status=400)
    
def delete(request, pk):
    try:
        contact = Contact.objects.get(pk=pk)
        contact.delete()
        return JsonResponse({"success": "Contact successfully deleted"})
    except Contact.DoesNotExist:
        return JsonResponse({"error": "Contact does not exists"})
        
def show(request, pk):
    try:
        contact = Contact.objects.filter(pk=pk)
        data = serializers.serialize('json', contact, fields=["name", "telephone", "address"])
        return JsonResponse({"contact": data})
    except Contact.DoesNotExist:
        return JsonResponse({"error": "Contact does not exists"})
    
@require_POST
def update(request, pk):
    try:
        contact = Contact.objects.get(pk=pk)
        form = UpdateContactForm(request.POST, instance=contact)
        form.save()
        return JsonResponse({"Successful": 'Contact Successfully Updated'})
    except Contact.DoesNotExist:
        return JsonResponse({"error": "Contact does not exists"})
    except ValueError:
        errors = form.errors.as_json()
        return JsonResponse({"errors": errors}, status=400)

crud/templates/crud/base_generic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Department For Transport Task</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'crud/my_styles.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <div class="container">
        {% include "crud/partials/navbar.html" %}
        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-12 ">
                {% block content %}{% endblock %}
                {% block pagination %}
                {% if is_paginated %}
                    <div class="pagination">
                        <span class="page-links">
                            {% if page_obj.has_previous %}
                                <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                            {% endif %}
                            <span class="page-current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>
                            {% if page_obj.has_next %}
                                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                            {% endif %}
                        </span>
                    </div>
                {% endif %}
                {% endblock %}
            </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

crud/templates/crud/contact.html
{% extends "crud/base_generic.html" %}

{% block content %}
    <div class="row">

        <div class="col-sm-12">
            <button type="button" id="show-add-new-contact-form" class="btn btn-success mt-1 float-end" data-bs-toggle="modal" data-bs-target="#exampleModal-oce">
                Create Contact
            </button>
        </div>

        <div class="col-sm-12">
            <div id="delete_contact"></div>
            <table class="table table-striped">
                <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Name</th>
                      <th scope="col">Telephone</th>
                      <th scope="col">Address</th>
                      <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>

                    {% if contacts %}
                        {% for contact in contacts %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ contact.name }}</td>
                                <td>{{ contact.telephone }}</td>
                                <td>{{ contact.address }}</td>
                                <td>
                                        <a href="#" title="Edit"><button class="btn btn-xs btn-info mx-2 mb-2" data-update-url="{% url 'crud:update' contact.id %}" data-edit-url="{% url 'crud:show' contact.id %}"  data-edit-contact="{{  contact.id }}"> Edit  </button> </a>
                                        <a href="#" title="Delete"><button class="btn btn-xs btn-danger mx-2 mb-2" data-delete-url="{% url 'crud:delete' contact.id %}" data-delete-contact="{{  contact.id }}"> Delete  </button> </a>
                                    

                                </td>
                            </tr>
                        {% endfor %}
                    
                    {% else %}
                        No Contact Address
                    {% endif %}

                </tbody>
            </table>

        </div>
    </div>
  {% include "crud/partials/add_form.html" %}
  {% include "crud/partials/edit_form.html" %}

  <script type="text/javascript">


    $(document).ready(function() {

        $(document).on('click','[data-delete-contact]',function(e) {
            e.preventDefault();
            e.preventDefault();
            $.ajaxSetup({headers: {'X-CSRF-TOKEN': $('input[name="csrfmiddlewaretoken"]').val()}});
            let edit = window.confirm('Are you sure you want to delete this Contact');
            const formData = {
                csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val(),
                id: $(this).attr('data-delete-contact')
            }

            if(edit == true){

                $.ajax({
                    data: formData, // get the form data
                    type: "GET",
                    url: $(this).attr('data-delete-url'),
                    cache: false,
                    processData:false,
                    contentType: false,
                    // on success
                    success: function (response) {
                        if(response.error)
                        {
                            $('#delete_contact').append('<li class="delete_portal_msg">'+response.error+'</li>');
                        } else {
                            alert('Contact Successfully deleted');
                            location.reload(true);
                        }
                    },
                    // on error
                    error: function (response) {
                        $('.backend-json-response').html('');
                        $('.backend-json-response').append('<span class="alert alert-danger mr-4" style="display:inline-block;"> '+response.responseJSON.errors+'</span>');
                    }
                });
                return false;

            } else {
                location.reload(true);
            }
        })
    })

  </script>


{% endblock %}

crud/templates/crud/partials/add_form.html
<!-- Modal -->
<div class="modal fade" id="new-contact-form" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Create Contact</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">

            <form>
                {% csrf_token %}
                <div id="role_error" class="backend-json-response"></div>
                <div class="mb-3">
                  <label for="recipient-name" class="col-form-label">Name</label>
                  <input type="text" class="form-control" id="name">
                </div>
                <div class="mb-3">
                    <label for="recipient-name" class="col-form-label">Telephone</label>
                    <input type="text" class="form-control" id="telephone">
                </div>
                <div class="mb-3">
                    <label for="message-text" class="col-form-label">Address</label>
                    <textarea class="form-control" id="address"></textarea>
                </div>
            </form>
         
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="add-new-contact">Save Contact</button>
        </div>
    </div>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function() {

        //Show Modal for New Contact Form
        $(document).on('click','#show-add-new-contact-form',function(e) {
            e.preventDefault();
            $.ajaxSetup({headers: {'X-CSRF-TOKEN': $('input[name="csrfmiddlewaretoken"]').val()}});
            // $('.backend-json-response').html('');
            $('#new-contact-form').modal('show');
        })

        $('#telephone').keyup(function () {
            // create an AJAX call
            $.ajax({
                data: $(this).serialize(), // get the form data
                url: "{% url 'crud:validate_telephone' %}",
                // on success
                success: function (response) {
                    if (response.is_taken == true) {
                        $('#telephoneError').remove();
                        $('#telephone').removeClass('is-valid').addClass('is-invalid');
                        $('#telephone').after('<div class="invalid-feedback d-block" id="telephoneError">This telephone is already associated to another person</div>')
                    }
                    else {
                        $('#telephone').removeClass('is-invalid').addClass('is-valid');
                        $('#telephoneError').remove();
                    }
                },
                // on error
                error: function (response) {
                    // alert the error if any error occured
                    console.log(response.responseJSON.errors)
                }
            });
            return false;
        })

        $(document).on('click','#add-new-contact',function(e) {
            e.preventDefault();
            e.preventDefault();
            $.ajaxSetup({headers: {'X-CSRF-TOKEN': $('input[name="csrfmiddlewaretoken"]').val()}});
            let formData = new FormData();
            formData.append('csrfmiddlewaretoken', $('input[name="csrfmiddlewaretoken"]').val());
            formData.append('name', $('#name').val());
            formData.append('telephone', $('#telephone').val());
            formData.append('address', $('#address').val());
            // create an AJAX call
            $.ajax({
                data: formData,
                type: "POST",
                url: "{% url 'crud:create' %}",
                cache: false,
                processData:false,
                contentType: false,
                // on success
                success: function (response) {
                    alert('Contact: (' + response.telephone + ') Successfully created');
                    window.setTimeout( function(){
                        $('#new-contact-form').modal('hide');
                        location.reload(true);
                    },1000);
                },
                // on error
                error: function (response) {
                    let errors = JSON.parse(response.responseJSON.errors);
                    $('.backend-json-response').html('');
                    $.each(errors, function(key, value){
                        $('.backend-json-response').append(
                            '<span class="alert alert-danger mr-4" style="display:inline-block;"> '+ key.toUpperCase() + ' : ' +value[0].message+'</span>'
                        );
                    });
                }
            });
            return false;
        })
    })

</script>

crud/templates/crud/partials/edit_form.html
<!-- Modal -->
<div class="modal fade" id="edit-contact-form" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Update Contact details</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">

            <form>
                {% csrf_token %}
                <div id="edit_error" class="backend-json-response"></div>
                <input type="hidden" class="form-control" id="edit-id">
                <input type="hidden" class="form-control" id="edit-url">
                <div class="mb-3">
                  <label for="recipient-name" class="col-form-label">Name</label>
                  <input type="text" class="form-control" id="edit-name">
                </div>
                <div class="mb-3">
                    <label for="recipient-name" class="col-form-label">Telephone</label>
                    <input type="text" class="form-control" id="edit-telephone">
                </div>
                <div class="mb-3">
                    <label for="message-text" class="col-form-label">Address</label>
                    <textarea class="form-control" id="edit-address"></textarea>
                </div>
            </form>
         
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="update-contact-details">Update Contact</button>
        </div>
    </div>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function() {

        //Show Modal for New Contact Form
        $(document).on('click','[data-edit-contact]',function(e) {
            e.preventDefault();
            $.ajaxSetup({headers: {'X-CSRF-TOKEN': $('input[name="csrfmiddlewaretoken"]').val()}});
            const formData = {
                csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val(),
                id: $(this).attr('data-edit-contact')
            };
            updateUrl = $(this).attr('data-update-url');
            $.ajax({
                data: formData, // get the form data
                url: $(this).attr('data-edit-url'),
                // on success
                success: function (response) {
                    if (response.error) {
                        $('#invalidError').remove();
                        $('#edit_error').removeClass('is-valid').addClass('is-invalid');
                        $('#edit_error').after('<div class="invalid-feedback d-block" id="invalidError">Invalid Contact details was selected</div>')
                    }
                    else {
                        let parseData = JSON.parse(response.contact);
                        $('#edit-name').val(parseData[0].fields.name);
                        $('#edit-telephone').val(parseData[0].fields.telephone);
                        $('#edit-address').val(parseData[0].fields.address);
                        $('#edit-id').val(parseData[0].pk);
                        $('#edit-url').val(updateUrl);
                        $('#edit-contact-form').modal('show');
                    }
                },
                // on error
                error: function (response) {
                    // alert the error if any error occured
                    console.log(response.responseJSON.errors)
                }
            });
            return false;
        })

        $(document).on('click','#update-contact-details',function(e) {
            e.preventDefault();
            e.preventDefault();
            $.ajaxSetup({headers: {'X-CSRF-TOKEN': $('input[name="csrfmiddlewaretoken"]').val()}});
            let formData = new FormData();
            formData.append('csrfmiddlewaretoken', $('input[name="csrfmiddlewaretoken"]').val());
            formData.append('name', $('#edit-name').val());
            formData.append('telephone', $('#edit-telephone').val());
            formData.append('address', $('#edit-address').val());
            formData.append('id', $('#edit-id').val());
            let url = $('#edit-url').val();
            // create an AJAX call
            $.ajax({
                data: formData,
                type: "POST",
                url: url,
                cache: false,
                processData:false,
                contentType: false,
                // on success
                success: function (response) {
                    alert('Contact: Successfully Updated');
                    window.setTimeout( function(){
                        $('#new-contact-form').modal('hide');
                        location.reload(true);
                    },1000);
                },
                // on error
                error: function (response) {
                    let errors = JSON.parse(response.responseJSON.errors);
                    $('.backend-json-response').html('');
                    $.each(errors, function(key, value){
                        $('.backend-json-response').append(
                            '<span class="alert alert-danger mr-4" style="display:inline-block;"> '+ key.toUpperCase() + ' : ' +value[0].message+'</span>'
                        );
                    });
                }
            });
            return false;
        })
    })

</script>

crud/templates/crud/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark  bg-primary mt-1">
    <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'crud:index' %}">Department For Transport Contact Task</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">


    </div>
    </div>
</nav>